img_host: "http://img.danishshowroom.cn/myj"
assets_host: "http://img.danishshowroom.cn"

defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts" 
    values:
      layout: "post"